# -*- coding: utf-8 -*-
"""VAE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wqa6UNatqGBUFQZW7Z2TxFKJjx6njKBg
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Appareil utilisé : {DEVICE}")

def get_mnist_loaders(val_ratio=0.1, batch_size=128, data_root="./data"):
    """
    Télécharge MNIST et renvoie les DataLoaders train/val/test.
    - val_ratio : proportion du train utilisée pour validation
    - batch_size : taille de batch
    - data_root  : dossier où stocker les données
    """

    transform = transforms.Compose([
        transforms.ToTensor(),
    ])

    # Dataset complet d'entraînement
    full_train_dataset = datasets.MNIST(
        root=data_root,
        train=True,
        download=True,
        transform=transform
    )

    # Split train / validation
    n_total = len(full_train_dataset)
    n_val = int(n_total * val_ratio)
    n_train = n_total - n_val

    train_dataset, val_dataset = random_split(
        full_train_dataset,
        [n_train, n_val],
        generator=torch.Generator().manual_seed(42)  # pour reproductibilité
    )

    # Dataset de test
    test_dataset = datasets.MNIST(
        root=data_root,
        train=False,
        download=True,
        transform=transform
    )

    # DataLoaders
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader   = DataLoader(val_dataset,   batch_size=batch_size, shuffle=False)
    test_loader  = DataLoader(test_dataset,  batch_size=batch_size, shuffle=False)

    print(f"Train : {len(train_dataset)} imgs, Val : {len(val_dataset)} imgs, Test : {len(test_dataset)} imgs")

    return train_loader, val_loader, test_loader

train_loader, val_loader, test_loader = get_mnist_loaders(batch_size=128)

class VariationalAutoencoder(nn.Module):
    def __init__(self, input_dim=784, hidden_dims=[256, 128], latent_dim=2):
        super().__init__()

        # 1. L'Encodeur
        encoder_layers, prev_dim = [], input_dim
        for h_dim in hidden_dims:
            encoder_layers.extend([nn.Linear(prev_dim, h_dim), nn.ReLU()])
            prev_dim = h_dim
        self.encoder = nn.Sequential(*encoder_layers)

        # 2. Séparation en mu et log-variance
        self.fc_mu = nn.Linear(prev_dim, latent_dim)
        self.fc_logvar = nn.Linear(prev_dim, latent_dim)

        # 3. Le Décodeur
        decoder_layers, prev_dim = [], latent_dim
        for h_dim in reversed(hidden_dims):
            decoder_layers.extend([nn.Linear(prev_dim, h_dim), nn.ReLU()])
            prev_dim = h_dim
        decoder_layers.extend([nn.Linear(prev_dim, input_dim), nn.Sigmoid()])
        self.decoder = nn.Sequential(*decoder_layers)

    def encode(self, x):
        h = self.encoder(x)
        return self.fc_mu(h), self.fc_logvar(h)

    def reparameterize(self, mu, logvar):
        # z = mu + sigma * epsilon
        std = torch.exp(0.5 * logvar) # Transformation log-variance -> écart-type
        eps = torch.randn_like(std)   # Bruit gaussien
        return mu + eps * std

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x):
        if x.dim() == 4:
            x = x.view(x.size(0), -1)
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        reconstructed_x = self.decode(z)
        return reconstructed_x, mu, logvar

def vae_loss_function(recon_x, x, mu, logvar):
    # 1. Erreur de reconstruction
    BCE = F.binary_cross_entropy(recon_x, x.view(-1, 784), reduction='sum')

    # 2. Divergence de Kullback-Leibler (KL)
    # Formule : -0.5 * sum(1 + log(sigma^2) - mu^2 - sigma^2)
    KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

    return BCE + KLD

import matplotlib.pyplot as plt


def train_vae(model, dataloader, epochs=15, lr=1e-3):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    model.train()


    loss_history = []

    for epoch in range(epochs):
        train_loss = 0
        for data, _ in dataloader:
            data = data.to(DEVICE)
            optimizer.zero_grad()

            recon_batch, mu, logvar = model(data)
            loss = vae_loss_function(recon_batch, data, mu, logvar)

            loss.backward()
            train_loss += loss.item()
            optimizer.step()

        # Calcul de la perte moyenne pour cette epoch
        avg_loss = train_loss / len(dataloader.dataset)

        # On ajoute la perte à la liste
        loss_history.append(avg_loss)
        print(f'Epoch {epoch+1} | VAE Loss: {avg_loss:.4f}')

    # La fonction retourne la liste des pertes à la fin de l'entraînement
    return loss_history

# 2. On réinitialise et on ré-entraîne le modèle
print("Début de l'entraînement...")
vae_model = VariationalAutoencoder(latent_dim=2).to(DEVICE)


history = train_vae(vae_model, train_loader, epochs=15)

# 3. courbe
plt.figure(figsize=(8, 5))


plt.plot(range(1, 16), history, marker='o', linestyle='-', color='#0284c7', linewidth=2, label="Perte d'entraînement (VAE)")

plt.title('Convergence de la fonction de perte globale (MSE + KL)', fontsize=14, fontweight='bold')
plt.xlabel('Nombre d\'Epochs', fontsize=12)
plt.ylabel('Perte Totale', fontsize=12)


plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()

# Affichage du graphique
plt.tight_layout()
plt.show()

def plot_latent_space(model, dataloader):
    """Génère le Scatter Plot de l'espace latent."""
    model.eval()
    z_coords, labels = [], []

    with torch.no_grad():
        for data, target in dataloader:
            data = data.to(DEVICE)
            mu, _ = model.encode(data.view(data.size(0), -1))
            z_coords.append(mu.cpu().numpy())
            labels.append(target.numpy())

    z_coords = np.concatenate(z_coords, axis=0)
    labels = np.concatenate(labels, axis=0)

    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(z_coords[:, 0], z_coords[:, 1], c=labels, cmap='tab10', alpha=0.7, s=5)
    plt.colorbar(scatter, ticks=range(10))
    plt.title("Visualisation 2D de l'Espace Latent du VAE")
    plt.xlabel("Dimension Latente z1")
    plt.ylabel("Dimension Latente z2")
    plt.grid(True, alpha=0.3)
    plt.show()

def plot_generated_manifold(model, grid_size=15, range_val=2.0):
    """Génère la grille de transition fluide (Manifold) en scannant l'espace latent."""
    model.eval()
    figure = np.zeros((28 * grid_size, 28 * grid_size))

    # Création d'une grille de coordonnées 2D (de -range_val à +range_val)
    grid_x = np.linspace(-range_val, range_val, grid_size)
    grid_y = np.linspace(range_val, -range_val, grid_size)

    with torch.no_grad():
        for i, yi in enumerate(grid_y):
            for j, xi in enumerate(grid_x):
                z_sample = torch.tensor([[xi, yi]], dtype=torch.float32).to(DEVICE)
                x_decoded = model.decode(z_sample).cpu().view(28, 28).numpy()
                figure[i * 28: (i + 1) * 28, j * 28: (j + 1) * 28] = x_decoded

    plt.figure(figsize=(10, 10))
    plt.imshow(figure, cmap='gray')
    plt.title("Images Générées en scannant l'Espace Latent")
    plt.axis('off')
    plt.show()

# Affichage des graphiques
plot_latent_space(vae_model, test_loader)
plot_generated_manifold(vae_model)